spring:
  application:
    name: scaling-disco
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.59.70:4000/scaling_disco?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: fx19950722.
    hikari:
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 600000
      maximum-pool-size: 20
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

server:
  port: 9001

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: assign_id

logging:
  level:
    com.re0.disco.mapper: debug

